// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: services.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto.Services {

  /// <summary>Holder for reflection information generated from services.proto</summary>
  public static partial class ServicesReflection {

    #region Descriptor
    /// <summary>File descriptor for services.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServicesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5zZXJ2aWNlcy5wcm90bxoObWVzc2FnZXMucHJvdG8aG2dvb2dsZS9wcm90",
            "b2J1Zi9lbXB0eS5wcm90bzJFChFOZWVkbGVQb3NlU2VydmljZRIwCgZVcGRh",
            "dGUSDC5Qb3NlU3RhbXBlZBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSIAMkcK",
            "EkxpdmVVU0ltYWdlU2VydmljZRIxCgZVcGRhdGUSDS5JbWFnZVN0YW1wZWQa",
            "Fi5nb29nbGUucHJvdG9idWYuRW1wdHkiADJBCg1VU01lc2hTZXJ2aWNlEjAK",
            "BlVwZGF0ZRIMLk1lc2hTdGFtcGVkGhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5",
            "IgBCEaoCDlByb3RvLlNlcnZpY2VzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Proto.Messages.MessagesReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
