// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: services.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto.Services {

  /// <summary>Holder for reflection information generated from services.proto</summary>
  public static partial class ServicesReflection {

    #region Descriptor
    /// <summary>File descriptor for services.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServicesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5zZXJ2aWNlcy5wcm90bxoObWVzc2FnZXMucHJvdG8aG2dvb2dsZS9wcm90",
            "b2J1Zi9lbXB0eS5wcm90bzI6CgtNZXNoU2VydmljZRIrCghTZW5kTWVzaBIF",
            "Lk1lc2gaFi5nb29nbGUucHJvdG9idWYuRW1wdHkiADI8CgtQb3NlU2Vydmlj",
            "ZRItCgpVcGRhdGVQb3NlEgUuUG9zZRoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0",
            "eSIAMjoKDEhlbGxvU2VydmljZRIqCghTYXlIZWxsbxINLkhlbGxvTWVzc2Fn",
            "ZRoNLkhlbGxvTWVzc2FnZSIAQhGqAg5Qcm90by5TZXJ2aWNlc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Proto.Messages.MessagesReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
